import { MonsterTemplate } from "../types";

export const MONSTERS: MonsterTemplate[] = [
    // 耕耘 / 大地
    { id: 'li_li', name: '狸力', en_name: 'Lili', tier: 1, maxHp: 50, theme: 'farming', 
      description: '像猪的野兽，爪子像鸡。它出现的地方，必定会大兴土木。', 
      en_description: 'A beast resembling a pig with chicken-like claws. Its appearance is a sign of major construction projects.', image: '' },
    { id: 'fei', name: '蜚', en_name: 'Fei', tier: 2, maxHp: 250, theme: 'farming', 
      description: '像牛的怪兽，蛇尾独眼。它经过的水源会干涸，草木会枯死，是瘟疫的象征。', 
      en_description: 'A monster like an ox, with a snake\'s tail and a single eye. Water sources dry up and plants wither where it passes. It is a symbol of plague.', image: '' },
    { id: 'meng_ji', name: '孟极', en_name: 'Mengji', tier: 3, maxHp: 500, theme: 'farming', 
      description: '形态像豹，额头为白色。善于隐藏自己，是山野中的伏击者。', 
      en_description: 'Resembles a leopard with a white forehead. It is skilled at hiding and ambushes its prey in the mountains.', image: '' },
    { id: 'fei_yi', name: '肥遗', en_name: 'Feiyi', tier: 4, maxHp: 1000, theme: 'farming', 
      description: '一头双身的怪蛇，它的出现预示着天下将有持续数年的大旱。', 
      en_description: 'A monstrous snake with one head and two bodies. Its appearance foretells a great drought that will last for years.', image: '' },
    { id: 'xiang_liu', name: '相柳', en_name: 'Xiangliu', tier: 5, maxHp: 2000, theme: 'farming', 
      description: '水神共工的臣子，九头蛇身。所到之处，土地变为剧毒沼泽，五谷不生。', 
      en_description: 'A minister of the water god Gonggong, with nine heads on a serpent\'s body. Wherever it goes, the land turns into a toxic swamp where no crops can grow.', image: '' },

    // 挖矿 / 山川
    { id: 'gu_chong', name: '蛊虫', en_name: 'Gu-bug', tier: 1, maxHp: 50, theme: 'mining', 
      description: '在阴暗潮湿的山中毒气中滋生的小虫，虽然单个很弱，但数量庞大，能侵蚀岩石。', 
      en_description: 'Small bugs bred from toxic gas in dark, damp mountains. Though individually weak, their vast numbers can erode rock.', image: '' },
    { id: 'tu_lou', name: '土蝼', en_name: 'Tulou', tier: 2, maxHp: 250, theme: 'mining', 
      description: '居住在昆仑之丘的食人野兽，长着四只角，形态像羊，性情凶猛。', 
      en_description: 'A man-eating beast from Mount Kunlun. It has four horns, looks like a goat, and is ferocious.', image: '' },
    { id: 'zao_chi', name: '凿齿', en_name: 'Zaochi', tier: 3, maxHp: 500, theme: 'mining', 
      description: '手持长戈，牙齿长如利凿的妖兽，能轻易咬碎金石。曾与英雄后羿大战。', 
      en_description: 'A beast with teeth as long as chisels, holding a long spear. It can easily crush metal and stone. It once fought the hero Hou Yi.', image: '' },
    { id: 'qiong_qi', name: '穷奇', en_name: 'Qiongqi', tier: 4, maxHp: 1000, theme: 'mining', 
      description: '上古四凶之一。外形像长着翅膀的老虎，扬善罚恶，专门吃掉正直的人。', 
      en_description: 'One of the Four Great Evils of antiquity. It looks like a tiger with wings. It punishes the good and rewards the evil, preying on the righteous.', image: '' },
    { id: 'tao_tie', name: '饕餮', en_name: 'Taotie', tier: 5, maxHp: 2000, theme: 'mining', 
      description: '上古四凶之一。贪食的象征，据说贪婪到吞食自己的身体，只剩一个巨大的头颅。', 
      en_description: 'One of the Four Great Evils of antiquity. A symbol of gluttony, so greedy it was said to have eaten its own body, leaving only a massive head.', image: '' },

    // 深海 / 水域
    { id: 'ren_yu', name: '人鱼', en_name: 'Mermaid', tier: 1, maxHp: 50, theme: 'sea', 
      description: '声音像婴儿啼哭，除了脸，全身都覆盖着鳞片。据说吃了它的肉可以长生。', 
      en_description: 'Its cry is like a baby\'s. Its body is covered in scales, except for its face. It is said that eating its flesh grants immortality.', image: '' },
    { id: 'chi_ru', name: '赤鱬', en_name: 'Chiru', tier: 2, maxHp: 250, theme: 'sea', 
      description: '人脸的鱼，叫声像鸳鸯。虽然外形可怖，但吃了它的肉据说可以治疗皮肤病。', 
      en_description: 'A fish with a human face. Its call sounds like a mandarin duck. Though frightening, its flesh is said to cure skin diseases.', image: '' },
    { id: 'xuan_gui', name: '旋龟', en_name: 'Xuangui (Whirl-turtle)', tier: 3, maxHp: 500, theme: 'sea', 
      description: '鸟头龟身，蛇尾。叫声像劈木头，佩戴它的甲壳可以治疗耳聋，防止失聪。', 
      en_description: 'A creature with a bird\'s head, a turtle\'s body, and a snake\'s tail. Its cry sounds like chopping wood. Wearing its shell can cure deafness.', image: '' },
    { id: 'hua_she', name: '化蛇', en_name: 'Huashe (Shapeshifting-snake)', tier: 4, maxHp: 1000, theme: 'sea', 
      description: '人面豺身，长着翅膀，蛇行。它的叫声像婴儿啼哭，出现的地方会引发滔天洪水。', 
      en_description: 'A creature with a human face, a jackal\'s body, wings, and slithers like a snake. Its cry is like a baby\'s, and its appearance causes great floods.', image: '' },
    { id: 'jiu_ying', name: '九婴', en_name: 'Jiuying (Nine-infant)', tier: 5, maxHp: 2000, theme: 'sea', 
      description: '有九个头的怪蛇，能喷射水火，叫声如婴儿啼哭。曾危害人间，后被后羿射杀。', 
      en_description: 'A nine-headed monster snake that can breathe fire and water. Its cry is like a baby\'s. It once plagued humanity before being slain by Hou Yi.', image: '' },

    // 宇宙 / 天空
    { id: 'qi_yu', name: '鵸鵌', en_name: 'Qiyu', tier: 1, maxHp: 50, theme: 'cosmos', 
      description: '三头六尾的怪鸟，样子像乌鸦。吃了它的肉可以不做噩梦，还能抵御凶邪。', 
      en_description: 'A strange bird with three heads and six tails, resembling a crow. Eating its flesh is said to prevent nightmares and ward off evil.', image: '' },
    { id: 'tian_gou', name: '天狗', en_name: 'Tiangou (Celestial-dog)', tier: 2, maxHp: 250, theme: 'cosmos', 
      description: '像狐狸却长着白色脑袋的野兽，叫声像猫。可以抵御凶邪，但其名也与“日食”相关。', 
      en_description: 'A beast like a fox with a white head. Its cry sounds like a cat. It can ward off evil, but its name is also associated with solar eclipses.', image: '' },
    { id: 'guan_guan', name: '灌灌', en_name: 'Guanguan', tier: 3, maxHp: 500, theme: 'cosmos', 
      description: '一种像鸽子的鸟，叫声会迷惑人心，使人忘记忧愁。虽然看似无害，但能扰乱人的心智。', 
      en_description: 'A bird resembling a dove. Its call can mesmerize people, making them forget their sorrows. Though seemingly harmless, it can disrupt the mind.', image: '' },
    { id: 'bi_fang', name: '毕方', en_name: 'Bifang', tier: 4, maxHp: 1000, theme: 'cosmos', 
      description: '独脚的火鸟，形态像鹤。它的出现预示着将有不明原因的大火灾发生。', 
      en_description: 'A one-legged fire bird that resembles a crane. Its appearance is a sign of a great, unexplained fire.', image: '' },
    { id: 'hun_dun', name: '浑沌', en_name: 'Hundun (Chaos)', tier: 5, maxHp: 2000, theme: 'cosmos', 
      description: '上古四凶之一。原始混沌之神，无面目，识歌舞。厌恶秩序，会帮助作恶之人。', 
      en_description: 'One of the Four Great Evils of antiquity. A primordial god of chaos, faceless, yet it understands song and dance. It despises order and aids evildoers.', image: '' },
];